fixes for opensuse sysvinit script

diff --git a/templates/suse/init.d/pyload.erb b/templates/suse/init.d/pyload.erb
--- a/templates/suse/init.d/pyload.erb
+++ b/templates/suse/init.d/pyload.erb
@@ -2,18 +2,27 @@
 ### BEGIN INIT INFO
 # Provides:          pyload
 # Required-Start:    $local_fs $remote_fs $network
+# Should-Start:
 # Required-Stop:     $local_fs $remote_fs $network
-# Default-Start:     2 3 4 5
-# Default-Stop:      0 1 6
+# Should-Stop:
+# Default-Start:     3 5
+# Default-Stop:      0 1 2 6
 # Short-Description: Downloadtool for One-Click-Hoster written in python.
 # Description:       Downloadtool for One-Click-Hoster written in python.
 ### END INIT INFO
 
 # Check daemon
-[ -x $DAEMON ] || exit 1
+test -x $DAEMON || { echo "$DAEMON not found";
+        if [ "$1" = "stop" ]; then exit 0;
+        else exit 5; fi; }
 
 # Read sysconfig
-[ -e /etc/sysconfig/pyload ] && . /etc/sysconfig/pyload
+if [ -f "/etc/sysconfig/pyload" ]; then
+    . /etc/sysconfig/pyload
+else
+    echo "config file /etc/sysconfig/pyload not found"
+    exit 6
+fi
 
 NAME="pyload"
 START_TIMEOUT=2
@@ -46,7 +55,8 @@ case "$1" in
         echo -n "Starting up $NAME "
         ## Start daemon with startproc(8). If this fails
         ## the return value is set appropriately by startproc.
-        /sbin/startproc -p $PIDFILE -u $USER -g $GROUP $DAEMON "$OPTIONS"
+        echo "whatever" 1>&2
+        /sbin/startproc -p $PIDFILE -u $USER -g $GROUP $DAEMON $OPTIONS
 
         # Remember status and be verbose
         rc_status -v
